package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/_GestionPersonalIntStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gusuarios.idl
* domingo 6 de marzo de 2022 13H51' COT
*/

public class _GestionPersonalIntStub extends org.omg.CORBA.portable.ObjectImpl implements s_gestion_usuarios.sop_corba.GestionPersonalInt
{

  public void registrarPersonal (s_gestion_usuarios.sop_corba.personalDTO objPersonal, org.omg.CORBA.BooleanHolder res)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarPersonal", true);
                s_gestion_usuarios.sop_corba.personalDTOHelper.write ($out, objPersonal);
                $in = _invoke ($out);
                res.value = $in.read_boolean ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registrarPersonal (objPersonal, res        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarPersonal

  public boolean consultarPersonal (int id, s_gestion_usuarios.sop_corba.personalDTOHolder objPersonal)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarPersonal", true);
                $out.write_long (id);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                objPersonal.value = s_gestion_usuarios.sop_corba.personalDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarPersonal (id, objPersonal        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarPersonal

  public void registrarUsuario (s_gestion_usuarios.sop_corba.usuarioDTO objUsuario, org.omg.CORBA.BooleanHolder res)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarUsuario", true);
                s_gestion_usuarios.sop_corba.usuarioDTOHelper.write ($out, objUsuario);
                $in = _invoke ($out);
                res.value = $in.read_boolean ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registrarUsuario (objUsuario, res        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarUsuario

  public boolean consultarUsuario (int id, s_gestion_usuarios.sop_corba.usuarioDTOHolder objUsuario)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarUsuario", true);
                $out.write_long (id);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                objUsuario.value = s_gestion_usuarios.sop_corba.usuarioDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarUsuario (id, objUsuario        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarUsuario

  public boolean abrirSesion (s_gestion_usuarios.sop_corba.credencialDTO objCredencial)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("abrirSesion", true);
                s_gestion_usuarios.sop_corba.credencialDTOHelper.write ($out, objCredencial);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return abrirSesion (objCredencial        );
            } finally {
                _releaseReply ($in);
            }
  } // abrirSesion

  public void registrarCallback (s_gestion_usuarios.sop_corba.AdmCllbckInt objCllbck)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarCallback", true);
                s_gestion_usuarios.sop_corba.AdmCllbckIntHelper.write ($out, objCllbck);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registrarCallback (objCllbck        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarCallback

  public void registrarCallbackFap (s_gestion_usuarios.sop_corba.FapCllbckInt objCllbck)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarCallbackFap", true);
                s_gestion_usuarios.sop_corba.FapCllbckIntHelper.write ($out, objCllbck);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registrarCallbackFap (objCllbck        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarCallbackFap

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionPersonalInt:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GestionPersonalIntStub
