package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/AdmCllbckIntPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gusuarios.idl
* domingo 6 de marzo de 2022 13H51' COT
*/

public class AdmCllbckIntPOATie extends AdmCllbckIntPOA
{

  // Constructors

  public AdmCllbckIntPOATie ( s_gestion_usuarios.sop_corba.AdmCllbckIntOperations delegate ) {
      this._impl = delegate;
  }
  public AdmCllbckIntPOATie ( s_gestion_usuarios.sop_corba.AdmCllbckIntOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public s_gestion_usuarios.sop_corba.AdmCllbckIntOperations _delegate() {
      return this._impl;
  }
  public void _delegate (s_gestion_usuarios.sop_corba.AdmCllbckIntOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void notificar (String nombreCompleto, int id)
  {
    _impl.notificar(nombreCompleto, id);
  } // notificar

  private s_gestion_usuarios.sop_corba.AdmCllbckIntOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class AdmCllbckIntPOATie
