package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/credencialDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gusuarios.idl
* domingo 6 de marzo de 2022 13H51' COT
*/

public final class credencialDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String usuario = null;
  public String clave = null;
  public int id = (int)0;

  public credencialDTO ()
  {
  } // ctor

  public credencialDTO (String _usuario, String _clave, int _id)
  {
    usuario = _usuario;
    clave = _clave;
    id = _id;
  } // ctor

} // class credencialDTO
