package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/FapCllbckIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gusuarios.idl
* domingo 6 de marzo de 2022 13H51' COT
*/

public interface FapCllbckIntOperations 
{
  void informarIngreso (String nombreCompleto, int id);
} // interface FapCllbckIntOperations
