package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/FapCllbckIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gusuarios.idl
* domingo 6 de marzo de 2022 13H51' COT
*/

public abstract class FapCllbckIntPOA extends org.omg.PortableServer.Servant
 implements s_gestion_usuarios.sop_corba.FapCllbckIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("informarIngreso", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/FapCllbckInt/informarIngreso
       {
         String nombreCompleto = in.read_string ();
         int id = in.read_long ();
         this.informarIngreso (nombreCompleto, id);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/FapCllbckInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FapCllbckInt _this() 
  {
    return FapCllbckIntHelper.narrow(
    super._this_object());
  }

  public FapCllbckInt _this(org.omg.CORBA.ORB orb) 
  {
    return FapCllbckIntHelper.narrow(
    super._this_object(orb));
  }


} // class FapCllbckIntPOA
