package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/GestionPersonalIntPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gusuarios.idl
* domingo 6 de marzo de 2022 13H51' COT
*/

public class GestionPersonalIntPOATie extends GestionPersonalIntPOA
{

  // Constructors

  public GestionPersonalIntPOATie ( s_gestion_usuarios.sop_corba.GestionPersonalIntOperations delegate ) {
      this._impl = delegate;
  }
  public GestionPersonalIntPOATie ( s_gestion_usuarios.sop_corba.GestionPersonalIntOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public s_gestion_usuarios.sop_corba.GestionPersonalIntOperations _delegate() {
      return this._impl;
  }
  public void _delegate (s_gestion_usuarios.sop_corba.GestionPersonalIntOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void registrarPersonal (s_gestion_usuarios.sop_corba.personalDTO objPersonal, org.omg.CORBA.BooleanHolder res)
  {
    _impl.registrarPersonal(objPersonal, res);
  } // registrarPersonal

  public boolean consultarPersonal (int id, s_gestion_usuarios.sop_corba.personalDTOHolder objPersonal)
  {
    return _impl.consultarPersonal(id, objPersonal);
  } // consultarPersonal

  public void registrarUsuario (s_gestion_usuarios.sop_corba.usuarioDTO objUsuario, org.omg.CORBA.BooleanHolder res)
  {
    _impl.registrarUsuario(objUsuario, res);
  } // registrarUsuario

  public boolean consultarUsuario (int id, s_gestion_usuarios.sop_corba.usuarioDTOHolder objUsuario)
  {
    return _impl.consultarUsuario(id, objUsuario);
  } // consultarUsuario

  public boolean abrirSesion (s_gestion_usuarios.sop_corba.credencialDTO objCredencial)
  {
    return _impl.abrirSesion(objCredencial);
  } // abrirSesion

  public void registrarCallback (s_gestion_usuarios.sop_corba.AdmCllbckInt objCllbck)
  {
    _impl.registrarCallback(objCllbck);
  } // registrarCallback

  public void registrarCallbackFap (s_gestion_usuarios.sop_corba.FapCllbckInt objCllbck)
  {
    _impl.registrarCallbackFap(objCllbck);
  } // registrarCallbackFap

  private s_gestion_usuarios.sop_corba.GestionPersonalIntOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class GestionPersonalIntPOATie
