package s_gestion_usuarios.sop_corba;

/**
* s_gestion_usuarios/sop_corba/GestionPersonalIntHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gusuarios.idl
* domingo 6 de marzo de 2022 13H51' COT
*/

public final class GestionPersonalIntHolder implements org.omg.CORBA.portable.Streamable
{
  public s_gestion_usuarios.sop_corba.GestionPersonalInt value = null;

  public GestionPersonalIntHolder ()
  {
  }

  public GestionPersonalIntHolder (s_gestion_usuarios.sop_corba.GestionPersonalInt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = s_gestion_usuarios.sop_corba.GestionPersonalIntHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    s_gestion_usuarios.sop_corba.GestionPersonalIntHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return s_gestion_usuarios.sop_corba.GestionPersonalIntHelper.type ();
  }

}
