package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/GestionPersonalIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gusuarios.idl
* domingo 6 de marzo de 2022 13H51' COT
*/

public interface GestionPersonalIntOperations 
{
  void registrarPersonal (s_gestion_usuarios.sop_corba.personalDTO objPersonal, org.omg.CORBA.BooleanHolder res);
  boolean consultarPersonal (int id, s_gestion_usuarios.sop_corba.personalDTOHolder objPersonal);
  void registrarUsuario (s_gestion_usuarios.sop_corba.usuarioDTO objUsuario, org.omg.CORBA.BooleanHolder res);
  boolean consultarUsuario (int id, s_gestion_usuarios.sop_corba.usuarioDTOHolder objUsuario);
  boolean abrirSesion (s_gestion_usuarios.sop_corba.credencialDTO objCredencial);
  void registrarCallback (s_gestion_usuarios.sop_corba.AdmCllbckInt objCllbck);
  void registrarCallbackFap (s_gestion_usuarios.sop_corba.FapCllbckInt objCllbck);
} // interface GestionPersonalIntOperations
