package s_seguimiento_usuarios.sop_corba;


/**
* s_seguimiento_usuarios/sop_corba/_GestionPacientesIntStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gpacientes.idl
* domingo 6 de marzo de 2022 13H51' COT
*/

public class _GestionPacientesIntStub extends org.omg.CORBA.portable.ObjectImpl implements s_seguimiento_usuarios.sop_corba.GestionPacientesInt
{

  public void registrarValoracion (s_seguimiento_usuarios.sop_corba.ValoracionDTO objValoracion, org.omg.CORBA.BooleanHolder res)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarValoracion", true);
                s_seguimiento_usuarios.sop_corba.ValoracionDTOHelper.write ($out, objValoracion);
                $in = _invoke ($out);
                res.value = $in.read_boolean ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registrarValoracion (objValoracion, res        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarValoracion

  public boolean consultarValoracion (int id, s_seguimiento_usuarios.sop_corba.ValoracionDTOHolder objValoracion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarValoracion", true);
                $out.write_long (id);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                objValoracion.value = s_seguimiento_usuarios.sop_corba.ValoracionDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarValoracion (id, objValoracion        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarValoracion

  public void registrarProgramaFisico (s_seguimiento_usuarios.sop_corba.ProgramaFisicoDTO objProgramaFisico, org.omg.CORBA.BooleanHolder res)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarProgramaFisico", true);
                s_seguimiento_usuarios.sop_corba.ProgramaFisicoDTOHelper.write ($out, objProgramaFisico);
                $in = _invoke ($out);
                res.value = $in.read_boolean ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registrarProgramaFisico (objProgramaFisico, res        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarProgramaFisico

  public boolean consultarProgramaFisico (int id, s_seguimiento_usuarios.sop_corba.ProgramaFisicoDTOHolder objProgramaFisico)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarProgramaFisico", true);
                $out.write_long (id);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                objProgramaFisico.value = s_seguimiento_usuarios.sop_corba.ProgramaFisicoDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarProgramaFisico (id, objProgramaFisico        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarProgramaFisico

  public void registrarAsistencia (s_seguimiento_usuarios.sop_corba.AsistenciaDTO objAsistencia, org.omg.CORBA.BooleanHolder res)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarAsistencia", true);
                s_seguimiento_usuarios.sop_corba.AsistenciaDTOHelper.write ($out, objAsistencia);
                $in = _invoke ($out);
                res.value = $in.read_boolean ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registrarAsistencia (objAsistencia, res        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarAsistencia

  public boolean consultarAsistencia (int id, s_seguimiento_usuarios.sop_corba.ArrayAsistenciaHolder lstAsistencia)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarAsistencia", true);
                $out.write_long (id);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                lstAsistencia.value = s_seguimiento_usuarios.sop_corba.ArrayAsistenciaHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarAsistencia (id, lstAsistencia        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarAsistencia

  public void contarFaltas (int id, org.omg.CORBA.IntHolder numFaltas)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("contarFaltas", true);
                $out.write_long (id);
                $in = _invoke ($out);
                numFaltas.value = $in.read_long ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                contarFaltas (id, numFaltas        );
            } finally {
                _releaseReply ($in);
            }
  } // contarFaltas

  public void enviarNotificacion (s_seguimiento_usuarios.sop_corba.notificacionDTO objNotificacion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("enviarNotificacion", true);
                s_seguimiento_usuarios.sop_corba.notificacionDTOHelper.write ($out, objNotificacion);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                enviarNotificacion (objNotificacion        );
            } finally {
                _releaseReply ($in);
            }
  } // enviarNotificacion

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionPacientesInt:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GestionPacientesIntStub
