package s_seguimiento_usuarios.sop_corba;


/**
* s_seguimiento_usuarios/sop_corba/GestionNotificacionesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gpacientes.idl
* sábado 5 de marzo de 2022 12H04' COT
*/

public interface GestionNotificacionesOperations 
{
  void enviarNotificacion (s_seguimiento_usuarios.sop_corba.GestionNotificacionesPackage.notificacionDTO objNotificacion);
} // interface GestionNotificacionesOperations
