package s_seguimiento_usuarios.sop_corba;


/**
* s_seguimiento_usuarios/sop_corba/GestionPacientes.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gpacientes.idl
* sábado 5 de marzo de 2022 10H24' COT
*/

public interface GestionPacientes extends GestionPacientesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionPacientes
