package s_seguimiento_usuarios.sop_corba;


/**
* s_seguimiento_usuarios/sop_corba/notificacionDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gpacientes.idl
* domingo 6 de marzo de 2022 13H51' COT
*/

public final class notificacionDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String nombreCompleto = null;
  public String ocupacion = null;

  public notificacionDTO ()
  {
  } // ctor

  public notificacionDTO (String _nombreCompleto, String _ocupacion)
  {
    nombreCompleto = _nombreCompleto;
    ocupacion = _ocupacion;
  } // ctor

} // class notificacionDTO
