package s_seguimiento_usuarios.sop_corba;


/**
* s_seguimiento_usuarios/sop_corba/ProgramaDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gpacientes.idl
* domingo 6 de marzo de 2022 13H51' COT
*/

abstract public class ProgramaDTOHelper
{
  private static String  _id = "IDL:sop_corba/ProgramaDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, s_seguimiento_usuarios.sop_corba.ProgramaDTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static s_seguimiento_usuarios.sop_corba.ProgramaDTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "dia",
            _tcOf_members0,
            null);
          _tcOf_members0 = s_seguimiento_usuarios.sop_corba.EjercicioDTOHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (s_seguimiento_usuarios.sop_corba.ArrayEjerciciosHelper.id (), "ArrayEjercicios", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "listaEjercicios",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (s_seguimiento_usuarios.sop_corba.ProgramaDTOHelper.id (), "ProgramaDTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static s_seguimiento_usuarios.sop_corba.ProgramaDTO read (org.omg.CORBA.portable.InputStream istream)
  {
    s_seguimiento_usuarios.sop_corba.ProgramaDTO value = new s_seguimiento_usuarios.sop_corba.ProgramaDTO ();
    value.dia = istream.read_long ();
    value.listaEjercicios = s_seguimiento_usuarios.sop_corba.ArrayEjerciciosHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, s_seguimiento_usuarios.sop_corba.ProgramaDTO value)
  {
    ostream.write_long (value.dia);
    s_seguimiento_usuarios.sop_corba.ArrayEjerciciosHelper.write (ostream, value.listaEjercicios);
  }

}
