package s_seguimiento_usuarios.sop_corba;


/**
* s_seguimiento_usuarios/sop_corba/ProgramaDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from gpacientes.idl
* domingo 6 de marzo de 2022 13H51' COT
*/

public final class ProgramaDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int dia = (int)0;
  public s_seguimiento_usuarios.sop_corba.EjercicioDTO listaEjercicios[] = null;

  public ProgramaDTO ()
  {
  } // ctor

  public ProgramaDTO (int _dia, s_seguimiento_usuarios.sop_corba.EjercicioDTO[] _listaEjercicios)
  {
    dia = _dia;
    listaEjercicios = _listaEjercicios;
  } // ctor

} // class ProgramaDTO
